from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    EVENT_ORGANIZER = "EVENT_ORGANIZER"
    SPEAKER = "SPEAKER"
    STAFF = "STAFF"
    ATTENDEE = "ATTENDEE"


class EventType(str, Enum):
    CONFERENCE = "CONFERENCE"
    WORKSHOP = "WORKSHOP"
    SEMINAR = "SEMINAR"
    MEETUP = "MEETUP"
    TRAINING = "TRAINING"


class EventStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    REGISTRATION_OPEN = "REGISTRATION_OPEN"
    REGISTRATION_CLOSED = "REGISTRATION_CLOSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class RegistrationStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    ATTENDED = "ATTENDED"

class TicketType(str, Enum):
    STANDARD = "STANDARD"
    VIP = "VIP"
    EARLY_BIRD = "EARLY_BIRD"
    STUDENT = "STUDENT"

class PaymentMethod(str, Enum):
    CARD = "CARD"
    UPI = "UPI"
    NET_BANKING = "NET_BANKING"
    WALLET = "WALLET"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class PurchaseStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class SessionBookingStatus(str, Enum):
    BOOKED = "BOOKED"
    CANCELLED = "CANCELLED"

class CheckInMethod(str, Enum):
    QR_CODE = "QR_CODE"
    MANUAL = "MANUAL"
    STAFF = "STAFF"

class CertificateType(str, Enum):
    PARTICIPATION = "PARTICIPATION"
    COMPLETION = "COMPLETION"
    EXCELLENCE = "EXCELLENCE"


class CertificateStatus(str, Enum):
    GENERATED = "GENERATED"
    REVOKED = "REVOKED"

class NotificationType(str, Enum):
    REGISTRATION_CONFIRMATION = "REGISTRATION_CONFIRMATION"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    EVENT_REMINDER = "EVENT_REMINDER"
    SESSION_REMINDER = "SESSION_REMINDER"
    CANCELLATION = "CANCELLATION"
    TICKET_CONFIRMATION = "TICKET_CONFIRMATION"
    CERTIFICATE_AVAILABLE = "CERTIFICATE_AVAILABLE"


class NotificationStatus(str, Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"

class RefundStatus(str, Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class RefundReason(str, Enum):
    EVENT_CANCELLED = "EVENT_CANCELLED"
    ATTENDEE_CANCELLED = "ATTENDEE_CANCELLED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    OTHER = "OTHER"

class AuditAction(str, Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    REGISTER = "REGISTER"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    EVENT_CREATED = "EVENT_CREATED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_DELETED = "EVENT_DELETED"
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    REFUND_REQUESTED = "REFUND_REQUESTED"
    REFUND_APPROVED = "REFUND_APPROVED"
    REFUND_REJECTED = "REFUND_REJECTED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"


class AuditStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"